### ISSUE TITLE
GNU GPL compatible license

### ISSUE THREAD

**Issue by kirantpatil** [ibaton/3House#60]
Hi,

Please use the GNU GPL compatible license.

http://www.gnu.org/licenses/license-list.en.html

Thanks.

**Comment by ibaton** [comment]
Hi @kirantpatil, Could you explain why?

**Comment by kirantpatil** [comment]
Hi @ibaton, I am raising this issue since EPL is not true Freesoftware.

**Comment by ibaton** [comment]
@kirantpatil I don't really fancy any opensource licenses in particular, I think that they most often are quite good. But I dont want to move over to using GPL if I don't have to. Especially since the main Openhab project is using EPL (https://github.com/openhab/openhab2/blob/master/LICENSE) and it could prevent the main project from using code from this repository if they wanted to.  

Does my thinking make sense? @Human what do you think?

**Comment by Human** [comment]
@ibaton I'm not sure how much code the core project would need to take from the Android client, and I don't know much about the EPL. I know a lot about the GPL, though. The license you choose should reflect your goals for the project. I do know that EPL and GPL aren't very compatible; you might have to get every contributor to give permission to have their contributions re-licensed under GPL if you wanted to fork the current EPL code base. That does sound like a lot of work, but it's still relatively early in the project's public lifecycle that it'd be doable. I'd certainly agree to license all my contributions as GPL if it's what you want.

All I can recommend is that you look at what can and can't be done with EPL vs GPL, specifically what companies would be allowed to do by using the code base to drive some product that they want to sell.

**Comment by ibaton** [comment]
We'll keep it as EPL for now. 
I think it would be a bigger contribution to the OpenHab project overall to keep it the same license as all the other OH stuff out there.
