### ISSUE TITLE
Hoe to create a SQLiteDatabase in android studio?How to store and retrive the data in SQLiteDatabase?

### ISSUE THREAD

**Issue by amarpulli1994** [ibaton/3House#67]
Hello sir,
we are creating the customization profiles in android studio.In android studio we are adding the some other activity layouts.In android how to store the data and retrived the data,then how to retriveing data pass to MainActivity.What to do things used for this king of work.Any things downloaded for this problem solving. I try do the this activity,but i didn't get the solution.I getting the error Unfortunately,name has stopped, while running the application in android device.In android device how to strore the data in database when click the save button.please help me...wait for your response.
System Environments:
OS:Fedora 22 (64 bit).
JAVA: JAVA 1.8
Android studio: Android studio 2.0(Beta 6).

**Comment by ibaton** [comment]
Hi @amarnathreddy44. Sorry for the late reply. 
I am actually working on a big update switching over the whole database to realm.io since Active Android is no longer beeing maintained. Addign things to the database would probably be a lot easier after that. 
It would be great if you could send me the crash exception out print from logcat. Would help out a lot.
